- name: Add Docker GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: install yum-utils
  yum: 
    name: 
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - iptables
#    - containerd-io #https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    - docker-ce
    - docker-ce-cli
    - python3
    state: present

# Install (Docker) python package.
- pip:
    name: docker

- name: start docker-ce
  service:
    name: docker
    state: started
