---
- name: USECASE2-AS3
  hosts: lb
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"
    F5_Admin_Port: "8443"
    F5_VIP_Name: Use-Case-3-VIP


  tasks:
    - name: GET ASM - Module Install Status
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/tm/sys/provision/asm"
        method: GET
        status_code: 200
        timeout: 300
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
      register: installed_status

    - name: PUSH DO - Install ASM if not Installed
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/declarative-onboarding/declare"
        method: POST
        body: "{{ lookup('template','j2/provision.j2', split_lines=False) }}"
        status_code: 202
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
      when: installed_status.json.level != "nominal"

    - name: PUSH AS3
      uri:
        url: "https://{{ ansible_host }}:8443/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','j2/configure_as3.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: false
      delegate_to: localhost
